server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kartik15nov/cloud-config-repo
          clone-on-start: true

logging:
  level:
    org.springframework.cloud: debug
    org.springframework.web: debug